# VpcId: "10.0.0.0/16"
Application: ServiantestApp
#Private Subnets where ECS tasks will be running
PrivateSubnets:
  - PrivateSubnetA
  - PrivateSubnetB
  - PrivateSubnetC
#The Public subnets where ALB will deployed into
PublicSubnets:
  - PublicSubnetA
  - PublicSubnetB
#Database port to connect to RDS
DbPort: 5432
#ECS loggrooup retention period
LogRetentionDays: 30
#The number of fargate ECS Tasks that must exists
MinConCount: 2
#The max number of fargate ECS Tasks that can exists
MaxConCount: 5
#The max CPU utilization before scalling event can occur.
AutoScalingTargetValue: 70
#ALB Access logs enable/disable
ALBAccessLogs: "false"
