- name: playbook to deploy app resources.
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    local_repository: "{{ playbook_dir }}"
    ArtifactsBucket: nehamits-artifacts-bucket
    cf_stack_name: "{{ EnvPrefix | lower }}-{{ Application | lower }}-app"
    # ApiRoutkeys:
    #   - ProjectAccountRoute: /bye
    #     ApiGwAccountRoute: /v1/bye
    #   - ProjectAccountRoute: /hello
    #     ApiGwAccountRoute: /v1/hello

  vars_files: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"

  tasks:
    - name: gather facts - ansible_date_time
      setup:
        filter: ansible_date_time

    - name: Safe Mode | Generate Changeset name
      set_fact:
        cf_changeset_name: "{{ 'CS' + ansible_date_time.iso8601_basic }}"

    - debug:
        msg: Var file is - "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"

    - name: Display variables.
      include_vars:
        file: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"
        name: variables

    - debug:
        msg: Variables are - "{{ variables }}"

    - name: Generate jinja YAML template
      template:
        src: app-cfn.yml
        dest: template/{{ EnvPrefix }}-app-cfn.yml

    - name: Capture AWS Account number
      shell: "{{ 'aws sts get-caller-identity --query Account --output text' }}"
      register: account

    - debug:
        msg: AWS Account number is - "{{ account.stdout }}"

    - name: Deploy a Cloudformation stack
      cloudformation:
        stack_name: "{{ cf_stack_name }}"
        state: "present"
        create_changeset: "no"
        template: template/{{ EnvPrefix }}-app-cfn.yml
        changeset_name: "{{ cf_changeset_name }}"
        template_parameters:
          DockerImage: "{{ EnvPrefix | lower }}-{{ Application | lower }}"
          Application: " {{ Application }}"
          EnvPrefix: "{{ EnvPrefix }}"
          MinConCount: "{{ MinConCount }}"
          MaxConCount: "{{ MaxConCount }}"
          DbSecretsArnSSM: "Database{{ EnvPrefix }}{{ Application }}DB-SecretsManager"
          S3AccesslogsBucket: "{{ ArtifactsBucket }}"
          ALBAccessLogs: "{{ ALBAccessLogs }}"
          AutoScalingTargetValue: "{{ AutoScalingTargetValue }}"
          Certificate: "acm-arn-{{ Application }}"
          EcrImageTag: "{{ EnvPrefix | lower }}-{{ Application }}-ECR-Tag"
          # VPCId: "{{ VPCId }}"
      register: cfn_facts
