- name: playbook to deploy rds resources.
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    local_repository: "{{ playbook_dir }}"
    ArtifactsBucket: nehamits-artifacts-bucket
    cf_stack_name: "{{ EnvPrefix | lower }}-{{ Application | lower }}-rds"
    # ApiRoutkeys:
    #   - ProjectAccountRoute: /bye
    #     ApiGwAccountRoute: /v1/bye
    #   - ProjectAccountRoute: /hello
    #     ApiGwAccountRoute: /v1/hello

  vars_files: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"

  tasks:
    - name: gather facts - ansible_date_time
      setup:
        filter: ansible_date_time

    - name: Safe Mode | Generate Changeset name
      set_fact:
        cf_changeset_name: "{{ 'CS' + ansible_date_time.iso8601_basic }}"

    - debug:
        msg: Var file is - "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"
    # - name: Create directory for template files for CFN
    #   file:
    #     path: "{{ local_repository }}/template"
    #     state: directory

    - name: Display variables.
      include_vars:
        file: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"
        name: variables

    - debug:
        msg: Variables are - "{{ variables }}"

    - name: Generate jinja YAML template
      template:
        src: rds-cfn.yml
        dest: template/{{ EnvPrefix }}-rds-cfn.yml

    # - name: Copy KeyRotation lambda code to template directory
    #   copy:
    #     src: "{{ local_repository }}/KeyRotationcode"
    #     dest: "{{ local_repository }}/template/"
    # - name: Copy WafRule update lambda code to template directory
    #   copy:
    #     src: "{{ local_repository }}/WafRuleUpdatecode"
    #     dest: "{{ local_repository }}/template/"
    # - name: Copy Cloudfront distribution update lambda code to template directory
    #   copy:
    #     src: "{{ local_repository }}/KeyRotationcode-phase2"
    #     dest: "{{ local_repository }}/template/"
    # - name: Copy key rollback lambda code to template directory
    #   copy:
    #     src: "{{ local_repository }}/KeyRollbackFunction"
    #     dest: "{{ local_repository }}/template/"
    # - name: Package Cloud Formation templates that contain LambdaFunction.
    #   shell: "aws cloudformation package --template-file template/{{ EnvPrefix }}-key-rotation-cfn.yml --s3-bucket {{ ArtifactsBucket }} --output-template-file template/{{ EnvPrefix }}-key-rotation-cfn-output.yml"
    - name: Deploy Postgres Cloudformation stack
      cloudformation:
        stack_name: "{{ cf_stack_name }}"
        state: "present"
        create_changeset: "no"
        template: template/{{ EnvPrefix }}-rds-cfn.yml
        changeset_name: "{{ cf_changeset_name }}"
        template_parameters:
          DbPort: "{{ DbPort }}"
          DBEngineVersion: "{{ DBEngineVersion }}"
          EnablePerformanceInsights: "{{ EnablePerformanceInsights }}"
          PerformanceInsightsRetention: "{{ PerformanceInsightsRetention }}"
          DBSnapshotIdentifier: "{{ DBSnapshotIdentifier }}"
          Application: "{{ Application }}"
          readrep: "{{ readrep }}"
          EnvPrefix: "{{ EnvPrefix }}"
          DBStorageType: "{{ DBStorageType }}"
          DBUser: "{{ DBUser }}"
          # DBPassword: "{{ DBPassword}}"
          DBInstanceIdentifier: "{{ EnvPrefix | lower }}-{{ Application | lower }}"
          DBSid: "{{ DBSid }}"
          DBAllocatedStorage: "{{ DBAllocatedStorage }}"
          DBInstanceClass: "{{ DBInstanceClass }}"
          # DBInstanceClassRO: "{{ DBInstanceClassRO }}"
          DBBackupRetention: "{{ DBBackupRetention }}"
          # DBKMSEncryption: "{{ DBKMSEncryption }}"
          MultiAZ: "{{ MultiAZ }}"
          DbSecretsArnSSM: "Database{{ EnvPrefix }}{{ Application }}DB-SecretsManager"
          # VPCId: "{{ VPCId }}"
      register: cfn_facts
      # tags:
      #   - keyRotation

    # - name: Safe Mode | Get details about each change
    #   shell: "{{ 'aws cloudformation describe-change-set --change-set-name ' + cf_changeset_name + ' --stack-name ' + cf_stack_name }}"
    #   register: aws_cfnsget_cs_result
    #   when: cfn_facts is changed

    # - name: Safe Mode | Show changeset changes
    #   debug:
    #     msg: |
    #       The changes CloudFormation will make:
    #       {{ (aws_cfnsget_cs_result.stdout | from_json)['Changes'] | to_yaml }}"
    #   when: cfn_facts is changed

    # - name: Safe Mode | Review Template Differences and press 'C' and return to Continue or 'A' and return to abort
    #   pause:
    #     echo: yes
    #   register: aws_cfnspause_result
    #   when: cfn_facts is changed

    # # - name: Safe Mode | Fail if aborted
    # #   fail:
    # #     msg: "Interrupted..."
    # #   when: aws_cfnspause_result.user_input | d('') | lower is search('a')

    # - name: Safe Mode | Execute Change sets
    #   shell: "{{ 'aws cloudformation execute-change-set --change-set-name ' + cf_changeset_name + ' --stack-name ' + cf_stack_name }}"
    #   when: cfn_facts is changed

    # - name: Poll cloudformation until its in a steady state
    #   cloudformation_info:
    #     stack_name: "{{ cf_stack_name }}"
    #   register: cfn_facts
    #   retries: "50"
    #   delay: "5"
    #   until: cfn_facts['cloudformation'][cf_stack_name]['stack_description']['stack_status'] in ["UPDATE_COMPLETE","CREATE_COMPLETE","ROLLBACK_COMPLETE","UPDATE_ROLLBACK_COMPLETE","DELETE_COMPLETE"]
    #   when: cfn_facts is changed
