version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing ansible and python
      - aws --version
      - pip3 install ansible==2.9.0

  build:
    commands:
      - echo Build started on `date`
      - cd Infra/NetworkInfra
      - ansible-playbook app-ansible.yml -e "EnvPrefix=$Environment" || exit 1
      - echo Build finished on `date`
  post_build:
    commands:
      - echo Build completed on `date`
