- name: playbook to deploy Netowrk resources.
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    local_repository: "{{ playbook_dir }}"
    ArtifactsBucket: nehamits-artifacts-bucket
    cf_stack_name: "{{ EnvPrefix | lower }}-network-infra"
    Application: ServiantestApp

  vars_files: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"

  tasks:
    - name: gather facts - ansible_date_time
      setup:
        filter: ansible_date_time

    - name: Safe Mode | Generate Changeset name
      set_fact:
        cf_changeset_name: "{{ 'CS' + ansible_date_time.iso8601_basic }}"

    - debug:
        msg: Var file is - "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"

    - name: Display variables.
      include_vars:
        file: "{{ local_repository }}/vars/{{ EnvPrefix }}.yml"
        name: variables

    - debug:
        msg: Variables are - "{{ variables }}"

    - name: Generate jinja YAML template
      template:
        src: NetworkInfra-cfn.yml
        dest: template/{{ EnvPrefix }}-NetworkInfra-cfn.yml

    - name: Deploy network infrastructure.
      cloudformation:
        stack_name: "{{ cf_stack_name }}"
        changeset_name: "{{ cf_changeset_name }}"
        create_changeset: no
        state: "present"
        template: "template/{{ EnvPrefix }}-NetworkInfra-cfn.yml"
        capabilities: CAPABILITY_NAMED_IAM
        region: "ap-southeast-2"
        template_parameters:
          EnvPrefix: "{{ EnvPrefix }}"
          VpcCidrBlock: "{{ VpcCidrBlock }}"
        tags:
          Stack: "{{ cf_stack_name }}"
          Application: "{{ Application }}"
          CreatedBy: "Amit Erande"
          Email: "erande.amit@gmail.com"
          Dept: "DevOps"
      register: cfn_facts
